### ISSUE TITLE
Internal Server Error

### ISSUE THREAD

**Issue by wunyee** [std4453/mikanarr#14]
部屬在unraid docker中
打開http://IP:12306/RSS/Classic 或是 http://IP:12306/RSS/MyBangumi?token=xxxx
都顯示Internal Server Error
沒辦法獲取RSS

部屬的command
```
/usr/local/emhttp/plugins/dynamix.docker.manager/scripts/docker run -d --name='mikanarr' --net='bridge' -e HOST_OS="Unraid" -e 'PUID'='1000' -e 'PGID'='100' -e 'SONARR_API_KEY'='AKP_KEY' -e 'SONARR_HOST'='http://SONARR_IP' -e 'ADMIN_USERNAME'='admin' -e 'ADMIN_PASSWORD'='mypassword' -p '12306:12306/tcp' -v '/mnt/user/appdata/mikanarr/data':'/usr/src/app/data':'rw' 'std4453/mikanarr'
```

log如下
```yarn run v1.22.17
$ dotenv node server/index.js
[HPM] Proxy created: / -> http://SONARR.IP
App started on port 12306
[0mGET /sonarr/series [32m200[0m 74.513 ms - -[0m
ReferenceError: offset is not defined
at route (/usr/src/app/server/rss.js:39:55)
at processTicksAndRejections (internal/process/task_queues.js:95:5)
[0mGET /RSS/MyBangumi?token=xxxx [31m500[0m 5455.872 ms - 21[0m```

**Comment by A1exMinatoooo** [comment]
遇到同样问题

我这边的场景是，添加pattern时，选择剧集点击保存之后，offset的输入框就直接消失了，无法继续输入

![image](https://user-images.githubusercontent.com/21982749/163668868-35d71066-0361-4628-9c89-10fbe6948415.png)

```GET /RSS/Classic 500 805.444 ms - 21
ReferenceError: offset is not defined
    at route (/usr/src/app/server/rss.js:39:55)
    at runMicrotasks (<anonymous>)
    at processTicksAndRejections (internal/process/task_queues.js:95:5)
```

**Comment by wunyee** [comment]
是否是少merge了這一行造成的?
https://github.com/std4453/mikanarr/pull/4/commits/68be4f8dece4db01d41b5616562bde63e3ffc0ad#diff-bcb729747c92e72c12e4590f736a334041a572c429756da8af60b6ab89c6be79R43

**Comment by LGinC** [comment]
+1 导出到csv是有设置offset的，但是日志里还是提示没有定义offset
![image](https://user-images.githubusercontent.com/15363011/164212712-f7c5ac85-db68-47f5-9590-ad13ba9951f5.png)
```bash
ReferenceError: offset is not defined
    at route (/usr/src/app/server/rss.js:39:55)
    at processTicksAndRejections (internal/process/task_queues.js:95:5)
GET /RSS/Bangumi?bangumiId=2698&subgroupid=203&offset=-25 500 2101.259 ms - 21
```

**Comment by zx900930** [comment]
可以参考这个[commit](https://github.com/InsulateJustf/mikanarr/commit/66cb78ebd6eb3f621707a107bcec06c66dc07abd)
也可以暂时用他的镜像justf/mikanarr
记得把/usr/src/app/data 改成 /data
