### ISSUE TITLE
1.1.3版docker镜像不能启动

### ISSUE THREAD

**Issue by TrickLin** [std4453/mikanarr#5]
log如下

> yarn run v1.22.15,
$ dotenv node server/index.js,
internal/fs/utils.js:332,
    throw err;,
    ^,
,
Error: ENOENT: no such file or directory, open 'data/jwt.key.pub',
    at Object.openSync (fs.js:497:3),
    at Object.readFileSync (fs.js:393:35),
    at Object.<anonymous> (/usr/src/app/server/jwt.js:4:19),
    at Module._compile (internal/modules/cjs/loader.js:1085:14),
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:1114:10),
    at Module.load (internal/modules/cjs/loader.js:950:32),
    at Function.Module._load (internal/modules/cjs/loader.js:790:12),
    at Module.require (internal/modules/cjs/loader.js:974:19),
    at require (internal/modules/cjs/helpers.js:93:18),
    at Object.<anonymous> (/usr/src/app/server/sonarr.js:4:21) {,
  errno: -2,,
  syscall: 'open',,
  code: 'ENOENT',,
  path: 'data/jwt.key.pub',
},
error Command failed with exit code 1.,
info Visit https://yarnpkg.com/en/docs/cli/run for documentation about this command.,
yarn run v1.22.15,
$ dotenv node server/index.js,
internal/fs/utils.js:332,
    throw err;,
    ^,
,
Error: ENOENT: no such file or directory, open 'data/jwt.key.pub',
    at Object.openSync (fs.js:497:3),
    at Object.readFileSync (fs.js:393:35),
    at Object.<anonymous> (/usr/src/app/server/jwt.js:4:19),
    at Module._compile (internal/modules/cjs/loader.js:1085:14),
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:1114:10),
    at Module.load (internal/modules/cjs/loader.js:950:32),
    at Function.Module._load (internal/modules/cjs/loader.js:790:12),
    at Module.require (internal/modules/cjs/loader.js:974:19),
    at require (internal/modules/cjs/helpers.js:93:18),
    at Object.<anonymous> (/usr/src/app/server/sonarr.js:4:21) {,
  errno: -2,,
  syscall: 'open',,
  code: 'ENOENT',,
  path: 'data/jwt.key.pub',
},
error Command failed with exit code 1.,
info Visit https://yarnpkg.com/en/docs/cli/run for documentation about this command.,
yarn run v1.22.15,
$ dotenv node server/index.js,
internal/fs/utils.js:332,
    throw err;,
    ^,
,
Error: ENOENT: no such file or directory, open 'data/jwt.key.pub',
    at Object.openSync (fs.js:497:3),
    at Object.readFileSync (fs.js:393:35),
    at Object.<anonymous> (/usr/src/app/server/jwt.js:4:19),
    at Module._compile (internal/modules/cjs/loader.js:1085:14),
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:1114:10),
    at Module.load (internal/modules/cjs/loader.js:950:32),
    at Function.Module._load (internal/modules/cjs/loader.js:790:12),
    at Module.require (internal/modules/cjs/loader.js:974:19),
    at require (internal/modules/cjs/helpers.js:93:18),
    at Object.<anonymous> (/usr/src/app/server/sonarr.js:4:21) {,
  errno: -2,,
  syscall: 'open',,
  code: 'ENOENT',,
  path: 'data/jwt.key.pub',
},
error Command failed with exit code 1.,
info Visit https://yarnpkg.com/en/docs/cli/run for documentation about this command.,
yarn run v1.22.15,
$ dotenv node server/index.js,
internal/fs/utils.js:332,
    throw err;,
    ^,
,
Error: ENOENT: no such file or directory, open 'data/jwt.key.pub',
    at Object.openSync (fs.js:497:3),
    at Object.readFileSync (fs.js:393:35),
    at Object.<anonymous> (/usr/src/app/server/jwt.js:4:19),
    at Module._compile (internal/modules/cjs/loader.js:1085:14),
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:1114:10),
    at Module.load (internal/modules/cjs/loader.js:950:32),
    at Function.Module._load (internal/modules/cjs/loader.js:790:12),
    at Module.require (internal/modules/cjs/loader.js:974:19),
    at require (internal/modules/cjs/helpers.js:93:18),
    at Object.<anonymous> (/usr/src/app/server/sonarr.js:4:21) {,
  errno: -2,,
  syscall: 'open',,
  code: 'ENOENT',,
  path: 'data/jwt.key.pub',
},
error Command failed with exit code 1.,
info Visit https://yarnpkg.com/en/docs/cli/run for documentation about this command.,
yarn run v1.22.15,
$ dotenv node server/index.js,
internal/fs/utils.js:332,
    throw err;,
    ^,
,
Error: ENOENT: no such file or directory, open 'data/jwt.key.pub',
    at Object.openSync (fs.js:497:3),
    at Object.readFileSync (fs.js:393:35),
    at Object.<anonymous> (/usr/src/app/server/jwt.js:4:19),
    at Module._compile (internal/modules/cjs/loader.js:1085:14),
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:1114:10),
    at Module.load (internal/modules/cjs/loader.js:950:32),
    at Function.Module._load (internal/modules/cjs/loader.js:790:12),
    at Module.require (internal/modules/cjs/loader.js:974:19),
    at require (internal/modules/cjs/helpers.js:93:18),
    at Object.<anonymous> (/usr/src/app/server/sonarr.js:4:21) {,
  errno: -2,,
  syscall: 'open',,
  code: 'ENOENT',,
  path: 'data/jwt.key.pub',
},
error Command failed with exit code 1.,
info Visit https://yarnpkg.com/en/docs/cli/run for documentation about this command.,
yarn run v1.22.15,
$ dotenv node server/index.js,
internal/fs/utils.js:332,
    throw err;,
    ^,
,
Error: ENOENT: no such file or directory, open 'data/jwt.key.pub',
    at Object.openSync (fs.js:497:3),
    at Object.readFileSync (fs.js:393:35),
    at Object.<anonymous> (/usr/src/app/server/jwt.js:4:19),
    at Module._compile (internal/modules/cjs/loader.js:1085:14),
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:1114:10),
    at Module.load (internal/modules/cjs/loader.js:950:32),
    at Function.Module._load (internal/modules/cjs/loader.js:790:12),
    at Module.require (internal/modules/cjs/loader.js:974:19),
    at require (internal/modules/cjs/helpers.js:93:18),
    at Object.<anonymous> (/usr/src/app/server/sonarr.js:4:21) {,
  errno: -2,,
  syscall: 'open',,
  code: 'ENOENT',,
  path: 'data/jwt.key.pub',
},
error Command failed with exit code 1.,
info Visit https://yarnpkg.com/en/docs/cli/run for documentation about this command.,
yarn run v1.22.15,
$ dotenv node server/index.js,
internal/fs/utils.js:332,
    throw err;,
    ^,
,
Error: ENOENT: no such file or directory, open 'data/jwt.key.pub',
    at Object.openSync (fs.js:497:3),
    at Object.readFileSync (fs.js:393:35),
    at Object.<anonymous> (/usr/src/app/server/jwt.js:4:19),
    at Module._compile (internal/modules/cjs/loader.js:1085:14),
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:1114:10),
    at Module.load (internal/modules/cjs/loader.js:950:32),
    at Function.Module._load (internal/modules/cjs/loader.js:790:12),
    at Module.require (internal/modules/cjs/loader.js:974:19),
    at require (internal/modules/cjs/helpers.js:93:18),
    at Object.<anonymous> (/usr/src/app/server/sonarr.js:4:21) {,
  errno: -2,,
  syscall: 'open',,
  code: 'ENOENT',,
  path: 'data/jwt.key.pub',
},
error Command failed with exit code 1.,
info Visit https://yarnpkg.com/en/docs/cli/run for documentation about this command.,
yarn run v1.22.15,
$ dotenv node server/index.js,
internal/fs/utils.js:332,
    throw err;,
    ^,
,
Error: ENOENT: no such file or directory, open 'data/jwt.key.pub',
    at Object.openSync (fs.js:497:3),
    at Object.readFileSync (fs.js:393:35),
    at Object.<anonymous> (/usr/src/app/server/jwt.js:4:19),
    at Module._compile (internal/modules/cjs/loader.js:1085:14),
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:1114:10),
    at Module.load (internal/modules/cjs/loader.js:950:32),
    at Function.Module._load (internal/modules/cjs/loader.js:790:12),
    at Module.require (internal/modules/cjs/loader.js:974:19),
    at require (internal/modules/cjs/helpers.js:93:18),
    at Object.<anonymous> (/usr/src/app/server/sonarr.js:4:21) {,
  errno: -2,,
  syscall: 'open',,
  code: 'ENOENT',,
  path: 'data/jwt.key.pub',
},
error Command failed with exit code 1.,
info Visit https://yarnpkg.com/en/docs/cli/run for documentation about this command.,
yarn run v1.22.15,
$ dotenv node server/index.js,
internal/fs/utils.js:332,
    throw err;,
    ^,
,
Error: ENOENT: no such file or directory, open 'data/jwt.key.pub',
    at Object.openSync (fs.js:497:3),
    at Object.readFileSync (fs.js:393:35),
    at Object.<anonymous> (/usr/src/app/server/jwt.js:4:19),
    at Module._compile (internal/modules/cjs/loader.js:1085:14),
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:1114:10),
    at Module.load (internal/modules/cjs/loader.js:950:32),
    at Function.Module._load (internal/modules/cjs/loader.js:790:12),
    at Module.require (internal/modules/cjs/loader.js:974:19),
    at require (internal/modules/cjs/helpers.js:93:18),
    at Object.<anonymous> (/usr/src/app/server/sonarr.js:4:21) {,
  errno: -2,,
  syscall: 'open',,
  code: 'ENOENT',,
  path: 'data/jwt.key.pub',
},
error Command failed with exit code 1.,
info Visit https://yarnpkg.com/en/docs/cli/run for documentation about this command.,
yarn run v1.22.15,
$ dotenv node server/index.js,
internal/fs/utils.js:332,
    throw err;,
    ^,
,
Error: ENOENT: no such file or directory, open 'data/jwt.key.pub',
    at Object.openSync (fs.js:497:3),
    at Object.readFileSync (fs.js:393:35),
    at Object.<anonymous> (/usr/src/app/server/jwt.js:4:19),
    at Module._compile (internal/modules/cjs/loader.js:1085:14),
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:1114:10),
    at Module.load (internal/modules/cjs/loader.js:950:32),
    at Function.Module._load (internal/modules/cjs/loader.js:790:12),
    at Module.require (internal/modules/cjs/loader.js:974:19),
    at require (internal/modules/cjs/helpers.js:93:18),
    at Object.<anonymous> (/usr/src/app/server/sonarr.js:4:21) {,
  errno: -2,,
  syscall: 'open',,
  code: 'ENOENT',,
  path: 'data/jwt.key.pub',
},
error Command failed with exit code 1.,
info Visit https://yarnpkg.com/en/docs/cli/run for documentation about this command.,
yarn run v1.22.15,
$ dotenv node server/index.js,
internal/fs/utils.js:332,
    throw err;,
    ^,
,
Error: ENOENT: no such file or directory, open 'data/jwt.key.pub',
    at Object.openSync (fs.js:497:3),
    at Object.readFileSync (fs.js:393:35),
    at Object.<anonymous> (/usr/src/app/server/jwt.js:4:19),
    at Module._compile (internal/modules/cjs/loader.js:1085:14),
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:1114:10),
    at Module.load (internal/modules/cjs/loader.js:950:32),
    at Function.Module._load (internal/modules/cjs/loader.js:790:12),
    at Module.require (internal/modules/cjs/loader.js:974:19),
    at require (internal/modules/cjs/helpers.js:93:18),
    at Object.<anonymous> (/usr/src/app/server/sonarr.js:4:21) {,
  errno: -2,,
  syscall: 'open',,
  code: 'ENOENT',,
  path: 'data/jwt.key.pub',
},
error Command failed with exit code 1.,
info Visit https://yarnpkg.com/en/docs/cli/run for documentation about this command.

**Comment by TrickLin** [comment]
自己解决了..到这边 https://dinochiesa.github.io/jwt/ 复制内容手动创建 jwt.key.pub 和 jwt.key 文件就可以了
