### ISSUE TITLE
docker镜像跑不起来

### ISSUE THREAD

**Issue by kolicime** [std4453/mikanarr#6]
在参照[#5](https://github.com/std4453/mikanarr/issues/5)添加了`jwt.key`和`jwt.key.pub`之后还是跑不起来，docker日志如下
我之前并没有接触过JWT，对node.js也不很了解，上述的公钥私钥都是直接填的网页自动生成的，不知是不是因为这个
如果可以希望开发者能完善一下文档
```
yarn run v1.22.15
$ dotenv node server/index.js
/usr/src/app/node_modules/http-proxy-middleware/dist/config-factory.js:38
        throw new Error(errors_1.ERRORS.ERR_CONFIG_FACTORY_TARGET_MISSING);
        ^

Error: [HPM] Missing "target" option. Example: {target: "http://www.example.org"}
    at Object.createConfig (/usr/src/app/node_modules/http-proxy-middleware/dist/config-factory.js:38:15)
    at new HttpProxyMiddleware (/usr/src/app/node_modules/http-proxy-middleware/dist/http-proxy-middleware.js:147:40)
    at createProxyMiddleware (/usr/src/app/node_modules/http-proxy-middleware/dist/index.js:16:28)
    at Object.<anonymous> (/usr/src/app/server/sonarr.js:9:3)
    at Module._compile (internal/modules/cjs/loader.js:1085:14)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:1114:10)
    at Module.load (internal/modules/cjs/loader.js:950:32)
    at Function.Module._load (internal/modules/cjs/loader.js:790:12)
    at Module.require (internal/modules/cjs/loader.js:974:19)
    at require (internal/modules/cjs/helpers.js:93:18)
error Command failed with exit code 1.
info Visit https://yarnpkg.com/en/docs/cli/run for documentation about this command.
```

**Comment by TrickLin** [comment]
可以参照一下 #3 修改一下环境变量

**Comment by kolicime** [comment]
> 可以参照一下 #3 修改一下环境变量

可以了，非常感谢！
